"""add lunch columns and schedule unique constraint

Revision ID: 9c2269ea2bfb
Revises: 160babc12a3f
Create Date: 2026-06-08 03:31:42.827764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c2269ea2bfb'
down_revision: Union[str, None] = '160babc12a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 0001 의 Base.metadata.create_all 은 "현재 모델" 기준으로 스키마를 만들기 때문에,
    # 빈 DB 에서는 이 인덱스(uq_schedule_doctor_time)와 lunch 컬럼이 이미 생성돼 있다.
    # 반면 과거에 0001 만 적용했던 기존 DB 에는 아직 없다. 두 경우 모두 안전하도록
    # IF [NOT] EXISTS 로 멱등(idempotent) 처리한다.
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_schedule_doctor_time "
        'ON "scheduleDB" (doctorid, confirmed_time) '
        "WHERE deleted_at IS NULL AND status != 'CANCELLED'"
    )
    op.execute('ALTER TABLE "vet_scheduleDB" ADD COLUMN IF NOT EXISTS lunch_start TIME')
    op.execute('ALTER TABLE "vet_scheduleDB" ADD COLUMN IF NOT EXISTS lunch_end TIME')
    op.execute('ALTER TABLE "vet_scheduleDB" DROP COLUMN IF EXISTS is_available')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vet_scheduleDB', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('vet_scheduleDB', 'lunch_end')
    op.drop_column('vet_scheduleDB', 'lunch_start')
    op.drop_index('uq_schedule_doctor_time', table_name='scheduleDB', postgresql_where=sa.text("deleted_at IS NULL AND status != 'CANCELLED'"))
    # ### end Alembic commands ###
