"""add lunch columns and schedule unique constraint

Revision ID: 9c2269ea2bfb
Revises: 160babc12a3f
Create Date: 2026-06-08 03:31:42.827764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c2269ea2bfb'
down_revision: Union[str, None] = '160babc12a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_schedule_doctor_time', 'scheduleDB', ['doctorid', 'confirmed_time'], unique=True, postgresql_where=sa.text("deleted_at IS NULL AND status != 'CANCELLED'"))
    op.add_column('vet_scheduleDB', sa.Column('lunch_start', sa.Time(), nullable=True))
    op.add_column('vet_scheduleDB', sa.Column('lunch_end', sa.Time(), nullable=True))
    op.drop_column('vet_scheduleDB', 'is_available')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vet_scheduleDB', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('vet_scheduleDB', 'lunch_end')
    op.drop_column('vet_scheduleDB', 'lunch_start')
    op.drop_index('uq_schedule_doctor_time', table_name='scheduleDB', postgresql_where=sa.text("deleted_at IS NULL AND status != 'CANCELLED'"))
    # ### end Alembic commands ###
